Updates for Chef 17
chef-cookbooks/chef-vault pull request #96
Opened 2021-05-12 22:56 UTC by ramereth

- Add support for Chef 17 by enabling `unified_mode` to resources
- Increase required Chef Infra Client version to >= 15.3
- Add `kitchen.dokken.yml` and enable Github CI testing
- Convert ServerSpec to InSpec

Signed-off-by: Lance Albertson <lance@osuosl.org>

2021-05-12 22:57 UTC, ramereth commented
This supersedes #95

2021-05-13 15:42 UTC, Xorima requested changes

2021-05-13 15:42 UTC, Xorima commented on .github/workflows/ci.yml
> +        uses: actionshub/chef-delivery@master
```suggestion
        uses: actionshub/chef-delivery@main
```

2021-05-13 15:42 UTC, Xorima commented on .github/workflows/ci.yml
> +        uses: actionshub/chef-install@master
```suggestion
        uses: actionshub/chef-install@main
```

2021-05-13 15:42 UTC, Xorima commented on .github/workflows/ci.yml
> +        uses: actionshub/kitchen-dokken@master
```suggestion
        uses: actionshub/kitchen-dokken@main
```

2021-11-10 19:48 UTC, closed without merging